
Public Module Events
    Public ReadOnly FactEnter As String = "FactEnter"
    Public ReadOnly FactExit As String = "FactExit"
    Public ReadOnly TestConstructorEnter As String = "TestConstructorEnter"
    Public ReadOnly TestConstructorExit As String = "TestConstructorExit"
    Public ReadOnly TestIteratorMethodEnter As String = "TestIteratorMethodEnter"
    Public ReadOnly TestIteratorMethodExit As String = "TestIteratorMethodExit"
    Public ReadOnly TestAsyncMethodEnter As String = "TestAsyncMethodEnter"
    Public ReadOnly TestAsyncMethodExit As String = "TestAsyncMethodExit"
    Public ReadOnly TestPropertySetterEnter As String = "TestPropertySetterEnter"
    Public ReadOnly TestPropertySetterExit As String = "TestPropertySetterExit"
    Public ReadOnly TestPropertyGetterEnter As String = "TestPropertyGetterEnter"
    Public ReadOnly TestPropertyGetterExit As String = "TestPropertyGetterExit"
    Public ReadOnly TestEventAddEnter As String = "TestEventAddEnter"
    Public ReadOnly TestEventAddExit As String = "TestEventAddExit"
    Public ReadOnly TestEventRemoveEnter As String = "TestEventRemoveEnter"
    Public ReadOnly TestEventRemoveExit As String = "TestEventRemoveExit"
    Public ReadOnly TestStaticConstructorEnter As String = "TestStaticConstructorEnter"
    Public ReadOnly TestStaticConstructorExit As String = "TestStaticConstructorExit"
    Public ReadOnly TestStaticMethodEnter As String = "TestStaticMethodEnter"
    Public ReadOnly TestStaticMethodExit As String = "TestStaticMethodExit"
    Public ReadOnly TestStaticIteratorMethodEnter As String = "TestStaticIteratorMethodEnter"
    Public ReadOnly TestStaticIteratorMethodExit As String = "TestStaticIteratorMethodExit"
    Public ReadOnly TestStaticAsyncMethodEnter As String = "TestStaticAsyncMethodEnter"
    Public ReadOnly TestStaticAsyncMethodExit As String = "TestStaticAsyncMethodExit"
    Public ReadOnly TestStaticPropertyGetterEnter As String = "TestStaticPropertyGetterEnter"
    Public ReadOnly TestStaticPropertyGetterExit As String = "TestStaticPropertyGetterExit"
    Public ReadOnly TestStaticPropertySetterEnter As String = "TestStaticPropertySetterEnter"
    Public ReadOnly TestStaticPropertySetterExit As String = "TestStaticPropertySetterExit"
    Public ReadOnly TestStaticEventAddEnter As String = "TestStaticEventAddEnter"
    Public ReadOnly TestStaticEventAddExit As String = "TestStaticEventAddExit"
    Public ReadOnly TestStaticEventRemoveEnter As String = "TestStaticEventRemoveEnter"
    Public ReadOnly TestStaticEventRemoveExit As String = "TestStaticEventRemoveExit"
End Module